apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-replicaset
  namespace: demo
spec:
  version: "4.1.7-v1"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    storageClassName: "managed-premium-retain"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
